# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-08 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facetouch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='default', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_stamp',
            field=models.CharField(default='', max_length=100),
        ),
    ]
