# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 22:13
from __future__ import unicode_literals

from django.db import migrations

sections = ['Beverages', 'Desserts', 'Main Course']


def load_sections(apps, schema_editor):
    Section = apps.get_model('facetouch', 'Section')
    for section in sections:
        section_object = Section()
        section_object.name = section
        section_object.save()


class Migration(migrations.Migration):
    dependencies = [
        ('facetouch', '0003_auto_20190313_1153'),
    ]

    operations = [
        migrations.RunPython(load_sections),
        # migrations.RunPython(load_items)
    ]
