# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 22:38
from __future__ import unicode_literals

from django.db import migrations

items = [
    {'name': 'Pineapple Punch',
     'description': 'None',
     'price': 4.0,
     'image_url': 'https://deliciouslysprinkled.com/wp-content/uploads/2018/05/Easy-Pineapple-Rum-Punch-Recipe-4.jpg',
     'section': 'Beverages',
     },
]


def load_items(apps, schema_editor):
    Item = apps.get_model('facetouch', 'Item')
    Image = apps.get_model('facetouch', 'Image')
    Section = apps.get_model('facetouch', 'Section')
    for item in items:
        item_object = Item()
        item_object.name = item['name']
        item_object.description = item['description']
        item_object.price = item['price']
        item_image = Image()
        item_image.url = item['image_url']
        item_image.save()
        item_object.image = item_image
        item_section = Section.objects.filter(name=item['section']).first()
        item_object.section = item_section
        item_object.save()


class Migration(migrations.Migration):
    dependencies = [
        ('facetouch', '0004_auto_load_section'),
    ]

    operations = [
        migrations.RunPython(load_items)

    ]
